from DatabaseHandler.firebaseConfigure import db
from DatabaseHandler import DBcontroller
from DatabaseHandler import firebaseConfigure
from DatabaseHandler.DBcontroller import getMainCategoryCount,getNumberOfClothes, getClothesList
